apiVersion: batch/v1
kind: Job
metadata:
  name: train-job-0
spec:

  template:
    spec:

      containers:
        - name: bench-box
          image: docker.io/cimartinezvillar/benchmark-trainer:cuda12.1base
          imagePullPolicy: IfNotPresent

          resources:
            limits:
              memory: 16G
              cpu: 4
              nvidia.com/gpu: 1
              ephemeral-storage: 50G #isaid 32GB + ~32pth=~25GB?
            requests:
              memory: 16G
              cpu: 4
              nvidia.com/gpu: 1
              ephemeral-storage: 50G

          volumeMounts:
            - mountPath: /data_pvc
              name: zipped-vol

            - mountPath: /log_pvc
              name: log-vol

            - mountPath: /dev/shm
              name: dshm              

          command: ["/bin/sh","-c"]
          args:
          - git clone https://github.com/UARK-AICV/AerialFormer.git;
            cd AerialFormer;
            mkdir ./data;
            cp /data_pvc/5potsdam.zip ./data/;
            # cp data_pvc/6potsdam.zip ./data/;
            # cp data_pvc/isaid.zip ./data/;
            # cp data_pvc/loveDA.zip ./data;
            unzip -q ./data/5potsdam.zip -d ./data/;
            # unzip -q cache/6potsdam.zip -d ./data/;
            # unzip -q cache/isaid.zip -d ./data/;
            # unzip -q cache/loveDA.zip -d ./data/;
            python3 tools/train.py configs/aerialformer/aerialformer_base_512x512_5_potsdam.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_base_512x512_6_potsdam.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_base_896x896_isaid.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_base_512x512_loveda.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_small_512x512_5_potsdam.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_small_512x512_6_potsdam.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_small_896x896_isaid.py;
            # python3 tools/train.py configs/aerialformer/aerialformer_small_512x512_loveda.py;
            cp -r ./work_dirs /log_pvc;
            mv /log_pvc/work_dirs /log_pvc/aerialformer_b_5potsdam;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_b_6potsdam;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_b_isaid;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_b_loveda;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_s_5potsdam;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_s_6potsdam;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_s_isaid;
            # mv /log_pvc/work_dirs /log_pvc/aerialformer_s_loveda;   

      volumes:
     - name: zipped-vol
        persistentVolumeClaim:
          claimName: lake-benchmark-data

      - name: log-vol
        persistentVolumeClaim:
          claimName: lake-benchmark-logs

      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 8G

      restartPolicy: Never

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                # - key: topology.kubernetes.io/region
                  # operator: In
                  # values:
                  # - us-central  
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                  - NVIDIA-GeForce-RTX-3090
                  # - NVIDIA-A100-SXM4-80GB
                  # - Tesla-V100-PCIE-16GB

  backoffLimit: 0