apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:

  template:
    spec:

      containers:
        - name: train-box
          image: docker.io/cimartinezvillar/dcnn-pytorch:cuda12.4base-ubuntu22.04
          imagePullPolicy: IfNotPresent

          resources:
            limits:
              memory: 48Gi
              cpu: 8
              nvidia.com/gpu: 1
              ephemeral-storage: 50Gi 
            requests:
              memory: 48Gi
              cpu: 8
              nvidia.com/gpu: 1
              ephemeral-storage: 50Gi

          volumeMounts:
            - mountPath: /cache
              name: cache-vol

            - mountPath: /chips_zipped_pvc
              name: zipped-vol

            - mountPath: /log_pvc
              name: log-vol

            - mountPath: /model_pvc
              name: model-vol

          command: ["/bin/sh","-c"]
          args:
          - git clone https://github.com/carlosmartinezvillar/S2-waterbodies.git;
            cp chips_zipped_pvc/chips.zip cache/;
            unzip -q cache/chips.zip -d cache/;
            mkdir /cache/model;
            cd S2-waterbodies/src;
            python3 train.py --data-dir /cache/chips --net-dir /cache/model --log-dir /log_pvc --params ../hpo/params.json --row 0;
            cp /cache/model/*.pth.tar /model_pvc;

      volumes:
      - name: cache-vol
        emptyDir: {}
          sizeLimit: 50G
          medium: Memory

      - name: zipped-vol
        persistentVolumeClaim:
          claimName: lake-chips-zipped

      - name: log-vol
        persistentVolumeClaim:
          claimName: lake-training-logs

      - name: model-vol
        persistentVolumeClaim:
          claimName: lake-weights

      restartPolicy: Never

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                # - key: topology.kubernetes.io/region
                #   operator: In
                #   values:
                #   - us-central  
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                  - NVIDIA-GeForce-RTX-3090

  backoffLimit: 1