apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:
  backoffLimit: 0
  template:
    spec:

      containers:
        - name: trainbox
          image: docker.io/cimartinezvillar/dcnn-pytorch:cuda12.4base-ubuntu22.04
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 48Gi
              cpu: 8
              nvidia.com/gpu: 1
            requests:
              memory: 48Gi
              cpu: 8
              nvidia.com/gpu: 1

          volumeMounts:
            - mountPath: /cache
              name: cache-vol
            - mountPath: /log_pvc
              name: log-vol

          command: ["/bin/sh","-c"]
          args:
          - git clone https://github.com/carlosmartinezvillar/S2-waterbodies.git;
            cp lake-chips-zipped/chips.zip -d cache/;
            unzip cache/chips.zip -d cache/;
            python3 /S2-waterbodies/src/train.py --data-dir /cache/chips ;

      initContainers:
        - name: copybox
          image: docker.io/cimartinezvillar/geo:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 16Gi
              cpu: 2
            requests:
              memory: 16Gi
              cpu: 2
          volumeMounts:
            - mountPath: /cache
              name: cache-vol
            - mountPath: /zipped_chips
              name: chips-vol
          command: ["/bin/sh","-c"]
          args:
          - cp zipped_chips/chips.zip /cache;
            unzip /cache/chips.zip -d /cache/chips;
            git clone https://github.com/carlosmartinezvillar/S2-waterbodies.git;

      volumes:
      - name: cache-vol
        emptyDir: {}
          sizeLimit: 50G
      - name: chips-vol
        persistentVolumeClaim:
          claimName: lake-chips-zipped
      - name: log-vol
        persistentVolumeClaim:
          claimName: training-logs

      restartPolicy: Never

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                # - key: topology.kubernetes.io/region
                #   operator: In
                #   values:
                #   - us-central  
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                  - NVIDIA-GeForce-RTX-3090
